### ISSUE TITLE
Remix runtime errors

### ISSUE THREAD

**Issue by kbachnik** [NethermindEth/starknet-remix-plugin#128]
After adding and activating the plugin I give permissions 4 times. Then in Starknet logo left sidebar I see this error :

```
Uncaught runtime errors:
×
ERROR
Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.get (https://cairo-remix-test.nethermind.io/static/js/bundle.js:7259:18)
    at https://cairo-remix-test.nethermind.io/static/js/bundle.js:2926:76
    at commitHookEffectListMount (https://cairo-remix-test.nethermind.io/static/js/bundle.js:47780:30)
    at commitPassiveMountOnFiber (https://cairo-remix-test.nethermind.io/static/js/bundle.js:49273:17)
    at commitPassiveMountEffects_complete (https://cairo-remix-test.nethermind.io/static/js/bundle.js:49245:13)
    at commitPassiveMountEffects_begin (https://cairo-remix-test.nethermind.io/static/js/bundle.js:49235:11)
    at commitPassiveMountEffects (https://cairo-remix-test.nethermind.io/static/js/bundle.js:49225:7)
    at flushPassiveEffectsImpl (https://cairo-remix-test.nethermind.io/static/js/bundle.js:51110:7)
    at flushPassiveEffects (https://cairo-remix-test.nethermind.io/static/js/bundle.js:51062:18)
    at performSyncWorkOnRoot (https://cairo-remix-test.nethermind.io/static/js/bundle.js:50279:7)
ERROR
Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.get (https://cairo-remix-test.nethermind.io/static/js/bundle.js:7259:18)
    at https://cairo-remix-test.nethermind.io/static/js/bundle.js:2926:76
    at commitHookEffectListMount (https://cairo-remix-test.nethermind.io/static/js/bundle.js:47780:30)
    at commitPassiveMountOnFiber (https://cairo-remix-test.nethermind.io/static/js/bundle.js:49273:17)
    at commitPassiveMountEffects_complete (https://cairo-remix-test.nethermind.io/static/js/bundle.js:49245:13)
    at commitPassiveMountEffects_begin (https://cairo-remix-test.nethermind.io/static/js/bundle.js:49235:11)
    at commitPassiveMountEffects (https://cairo-remix-test.nethermind.io/static/js/bundle.js:49225:7)
    at flushPassiveEffectsImpl (https://cairo-remix-test.nethermind.io/static/js/bundle.js:51110:7)
    at flushPassiveEffects (https://cairo-remix-test.nethermind.io/static/js/bundle.js:51062:18)
    at performSyncWorkOnRoot (https://cairo-remix-test.nethermind.io/static/js/bundle.js:50279:7)
ERROR
Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.get (https://cairo-remix-test.nethermind.io/static/js/bundle.js:7259:18)
    at https://cairo-remix-test.nethermind.io/static/js/bundle.js:2926:76
    at commitHookEffectListMount (https://cairo-remix-test.nethermind.io/static/js/bundle.js:47780:30)
    at commitPassiveMountOnFiber (https://cairo-remix-test.nethermind.io/static/js/bundle.js:49273:17)
    at commitPassiveMountEffects_complete (https://cairo-remix-test.nethermind.io/static/js/bundle.js:49245:13)
    at commitPassiveMountEffects_begin (https://cairo-remix-test.nethermind.io/static/js/bundle.js:49235:11)
    at commitPassiveMountEffects (https://cairo-remix-test.nethermind.io/static/js/bundle.js:49225:7)
    at flushPassiveEffectsImpl (https://cairo-remix-test.nethermind.io/static/js/bundle.js:51110:7)
    at flushPassiveEffects (https://cairo-remix-test.nethermind.io/static/js/bundle.js:51062:18)
    at performSyncWorkOnRoot (https://cairo-remix-test.nethermind.io/static/js/bundle.js:50279:7)
```

In Plugin Manager Permissions  - No Permission requested yet.

How to fix this?

**Comment by EdgarBarrantes** [comment]
@kbachnik quick question, are you using Brave with Shields on?

**Comment by kbachnik** [comment]
> @kbachnik quick question, are you using Brave with Shields on?
No, just Chrome

**Comment by stranger80** [comment]
@kbachnik, can we ask you for a few more details of this behaviour? We suspect what may be the problem, but to be clear, would you like to fill in the details as per below?

**To Reproduce**
Steps to reproduce the behavior (from a clean start):
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Cairo files**
Please include the Cairo source file.

**Starknet Remix Plugin details**
- Are you using the default Starknet plugin from Remix marketplace, or any self-configured plugin instance?
- What Environment are you using (Remote/Local Devnet, a wallet configuration)?

**Host system (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari], any nonstandard browser plugins/adblocks
 - Version [e.g. 22]

**Comment by kbachnik** [comment]
Go to: https://remix.ethereum.org/#lang=en&optimize=false&runs=200&evmVersion=null&version=soljson-v0.8.18+commit.87f61d96.js
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/91157ef4-94b0-4398-b4d5-63cab9d1def7)

Click on : Plugin Manager 
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/7f2ff49e-9f1a-4c5a-b5eb-2bb675260b15)

Searching: Starknet
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/92fb027b-4e1b-4cfa-b9f4-0626210da8ab)

Click on Activate

Permissions Accept :
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/4517f60a-7599-4af7-bdd6-236b89970ef6)

Write file permission error: Error from IDE : [TIMEOUT] Timeout for call writeFile from Starknet
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/49d17d1f-f7b4-4e01-b3e3-ddfb36ed9327)

Checking the Permissions tab :
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/b173e815-ab1f-415b-b37f-dc60bd9e5a29)

Checking the Straknet logo on the sidebar :
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/121ef258-6eb0-4a0d-bbbe-763903a21e85)

Then i refreshed the page and checked the Starknet logo again :
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/ff054fe5-9f7d-470c-8bac-d6bb77e206e9)


---------------------------------------------------------------------------------------------------------------------------------------
Second try

Go to: https://remix.ethereum.org/#lang=en&optimize=false&runs=200&evmVersion=null&version=soljson-v0.8.18+commit.87f61d96.js
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/91157ef4-94b0-4398-b4d5-63cab9d1def7)

Click on : Plugin Manager 
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/7f2ff49e-9f1a-4c5a-b5eb-2bb675260b15)

Searching: Starknet
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/92fb027b-4e1b-4cfa-b9f4-0626210da8ab)

Click on Activate

First Permission Accept :
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/4517f60a-7599-4af7-bdd6-236b89970ef6)

Second Repmission Accept :
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/1ae89bca-5c27-4a2f-b4a6-d6cb18880f25)

Tird Repmission Accept :
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/8c9087a1-79e3-4a83-977d-5532aeb1c57f)

Fourth Repmission Accept :
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/2d2050a6-fcc5-4d21-bb86-bce39b74ba8c)

Write file permission error: Error from IDE : [TIMEOUT] Timeout for call writeFile from Starknet
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/49d17d1f-f7b4-4e01-b3e3-ddfb36ed9327)

Checking the Permissions tab :
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/b173e815-ab1f-415b-b37f-dc60bd9e5a29)

Checking the Straknet logo on the sidebar :
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/121ef258-6eb0-4a0d-bbbe-763903a21e85)

Then i refreshed the page and checked the Starknet logo again :
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/ff054fe5-9f7d-470c-8bac-d6bb77e206e9)

===============================================================================


I am using this instruction from nethermind-eth
https://medium.com/nethermind-eth/unlocking-onboarding-to-starknet-an-overview-of-the-starknet-remix-plugin-6b0658e73521


The time, when i indicate the Error - 00:50-01:05UTC


Im using the default Starknet plugin from Remix

Im using a wallet configuration


All Cairo files that i have :
[hello_world.zip](https://github.com/NethermindEth/starknet-remix-plugin/files/12720980/hello_world.zip)


System Spec :
OS - Windows 11 Version 10.0.22621 Build 22621
Browser - Chrome Version 116.0.5845.188 (Official Build) (64-bit)

**Comment by stranger80** [comment]
@kbachnik thank you for your patience in getting all the details to us! Your attempts appear to have coincided with plugin backend outages which we have experienced during the last 48 hours. We believe we have rectified these now - would you like to give the plugin another spin and confirm it is now compiling as expected?

**Comment by henryf10h** [comment]
hello! I am getting a similar error. 

To Reproduce
Steps to reproduce the behavior (from a clean start):

Go to Remix.
Since we're using Brave, turn off 'Shields Up'.
Re-open Remix.
Click on the extensions and search for the StarkNet plugin.
Click on the StarkNet plugin. 
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/55424527/61964e88-38bc-46e8-897b-141e4b0040f1)

See error: The plugin appears activated, but it doesn't redirect to the permissions window, and there's no option to compile the Cairo contract.

**Comment by kbachnik** [comment]
> @kbachnik thank you for your patience in getting all the details to us! Your attempts appear to have coincided with plugin backend outages which we have experienced during the last few days. We believe we have rectified these now - would you like to give the plugin another spin and confirm it is now compiling as expected?

![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/9b0441e1-be02-49a8-9760-cd5a65141aa5)

Same error today

**Comment by stranger80** [comment]
@henryf10h I see in your URL bar that you have been trying to connect to Remix/Starknet plugin using an external link, with incorrect `activate` parameter - the correct value is `activate=Starknet` (as opposed to `activate=Starknet-cairo1-compiler` on your screenshot). In other words, you seem to be using an old external reference link. Try: https://remix.ethereum.org/#activate=Starknet

**Comment by stranger80** [comment]
@henryf10h An empty plugin panel indicates the plugin hasn't loaded. This can be caused by connectivity problems - the following link must work from your browser, and must return a blank screen (with React-related HTML markup visible in page source): https://cairo-remix-test.nethermind.io/ . Can you test that and confirm the URL responds correctly. 

Note: The plugin, when launched, must be able to connect to following URLs as well:
- https://cairo-compile-remix-test.nethermind.io/health should respond with `OK`
- https://starknet-devnet-dev.nethermind.io/feeder_gateway/get_transaction_status?transactionHash=0xbadfad should respond with `{"tx_status":"NOT_RECEIVED"}`

Note2: I see in your URL bar that you have been trying to connect to Remix/Starknet plugin using an external link, with incorrect `activate` parameter - the correct value is `activate=Starknet` (as opposed to `activate=Starknet-cairo1-compiler` on your screenshot). In other words, you seem to be using an old external reference link - the correct one is: https://remix.ethereum.org/#activate=Starknet

**Comment by stranger80** [comment]
@kbachnik we were digging a bit deeper in the symptoms you are observing. The stacktrace error indicates that the browser is blocking access to `localStorage` element of the webpage. Possible causes are:  

   - Chrome is launched in incognito mode
   - Chrome setting "Block third-party cookies" is activated (see [chrome://settings/cookies](chrome://settings/cookies)):
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/12142580/53a50f43-757c-4331-a91e-8b395c7df97c)

Note: even with "Block third-party cookies" activate, exceptions can be added to a whitelist - the whitelist must include:
     - https://remix.ethereum.org
     - https://cairo-remix-test.nethermind.io

   - ...also see this [link](https://stackoverflow.com/questions/30481516/iframe-in-chrome-error-failed-to-read-localstorage-from-window-access-deni) for potential hints.

I hope this helps now.

**Comment by henryf10h** [comment]
Hello @stranger80 , 
So far, I have done the following:
1. I went to [https://cairo-remix-test.nethermind.io/](url) and I still got a white screen.
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/55424527/bb5372f5-eff5-4c2d-8edd-06b1f9615a29)
2. Then I connected to the next two links you have suggested to me, in both cases I got the expected responses ('ok' and '{"tx_status":"NOT_RECEIVED"}').
3. finally I go to the final link [https://remix.ethereum.org/#activate=Starknet](url) and I still can not see anything to compile. 
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/55424527/ec13229b-70c6-4665-8cba-3f8fb081ba35)

**Comment by stranger80** [comment]
@henryf10h would you like to join our Telegram channel (as posted on the repo's main README.md header)? Seems like something is interfering with js code on the Remix page, but that requires more sophisticated debugging (eg. clear the js console and network traces, restart Remix UI from the https://remix.ethereum.org/#activate=Starknet and watch Console and Network for errors...)

**Comment by henryf10h** [comment]
I cleared js console and network traces. After restarting I got the following errors:
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/55424527/cf9fe2e0-59b2-43f5-85bd-c2191757b487)
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/55424527/5f2515e0-c80a-46f9-b423-01bb90248257)
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/55424527/543957e0-eff6-4543-a200-4b96f74ecb11)
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/55424527/5c986228-96b4-45b3-bb63-6833e94a458b)
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/55424527/ac3f1dc7-78b3-4a17-bb8a-d019cf7ae64f)

**Comment by EdgarBarrantes** [comment]
@henryf10h @kbachnik by any chance, are any other Remix plugins working for you right now?

You might want to try using a VPN, there has been issues reported in our [telegram](https://t.me/StarknetRemixPlugin) regarding the list of plugins not showing due to location restrictions.

**Comment by kbachnik** [comment]
@EdgarBarrantes other Remix plugins work well
I have tried all the steps with VPN enabled but the error remains the same

**Comment by henryf10h** [comment]
ok, I just used VPN, and I still get the same. 

pd: I can not see other plugins such as tenderly.

**Comment by EdgarBarrantes** [comment]
Thanks for your patience and reports :)

@henryf10h, could you try out connecting to a different server? E.g.: France, USA? If you can't see the other plugins it's most likely the location issue reported in Telegram unrelated to this plugin.

@kbachnik, do you think you could clean cache ("Clear site data" in the Application tab in developer tools) and reload, we made some changes that should fix the timeout (we're working on more [optimisations](https://github.com/NethermindEth/starknet-remix-plugin/issues/131)), also, be sure you're not getting running in incognito mode / blocking 3rd party cookies like stranger80 said. Thanks a lot.

**Comment by kbachnik** [comment]
@EdgarBarrantes Same error
![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/36343167/556bad9f-d0d8-4c6a-80fb-772df728e86d)

**Comment by henryf10h** [comment]
Hello @EdgarBarrantes ,

I still get the same blank page even if I set the VPN to USA.

![image](https://github.com/NethermindEth/starknet-remix-plugin/assets/55424527/092e9ff4-a87a-4e2a-acdb-e9279ca82ca0)
